# .cirrus.yml

workflow:
  main:
    jobs:
      - generate_vendor_tree

jobs:
  generate_vendor_tree:
    docker_image: ghcr.io/sushrut1101/docker:arch
    steps:
      - name: Clone ROM repository
        command: |
          git clone https://github.com/rom-org/rom-repo.git /tmp/rom-repo

      - name: Generate Vendor Tree
        command: |
          cd /tmp/rom-repo
          # Add commands to generate the vendor tree from the ROM dump

      - name: Upload Vendor Tree Artifact
        artifacts:
          paths:
            - /tmp/rom-repo/vendor

