version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: ghcr.io/sushrut1101/docker:arch
        
jobs:
  my-job-name:

    executor: my-custom-executor
    steps:
      - checkout
      - run: |
         ssh-keyscan -t rsa gitlab.com >> ~/.ssh/known_hosts
         ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
         chmod 600 ~/.ssh/id_rsa
         cd ~/.ssh
         cat id_rsa.pub
        
         
         git clone https://github.com/nobiraja/android_device_oneplus_CPH2381.git device/oneplus/CPH2381
         git clone https://github.com/LineageOS/android_tools_extract-utils.git tools/extract-utils
         git clone https://github.com/LineageOS/android_prebuilts_extract-tools.git prebuilts/extract-tools
         ls
         cd device/oneplus/CPH2381
         ls
         chmod u+x setup-makefile.sh
         chmod u+x extract-files.sh
         ./setup-makefile.sh
         ./extract-files.sh ~/cph2381
workflows:
  my-custom-workflow:
    jobs:
      - my-job-name
