version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: ghcr.io/sushrut1101/docker:arch
        
jobs:
  my-job-name:

    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          # echo Hello, World!

workflows:
  my-custom-workflow:
    jobs:
      - my-job-name
