name: My Custom Workflow

on: [push, pull_request]

jobs:
  my-job-name:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/sushrut1101/docker:arch

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      

      - name: Configure Git
        run: |
          git config --global user.name "nobiraja"
          git config --global user.email "as3776958@gmail.com"

      - name: Clone repositories
        run: |
          git clone https://www.opencode.net/romdumprx/oneplus/CPH2381.git -b qssi-user-14-UKQ1.230924.001-1713196074550-release-keys-30875 ~/holi 
          git clone https://github.com/phhgsi/vendor_oneplus_oscar.git ~/holi/R
          git clone https://github.com/phhgsi/oplus_camera_lib.git ~/holi/oplus
          git clone https://github.com/phhgsi/android_device_oneplus_CPH2381.git device/oneplus/CPH2381
          git clone https://github.com/LineageOS/android_tools_extract-utils.git tools/extract-utils
          git clone https://github.com/LineageOS/android_prebuilts_extract-tools.git prebuilts/extract-tools

      - name: List directories
        run: ls

      - name: Setup and Extract files
        run: |
          cd device/oneplus/CPH2381
          chmod u+x setup-makefiles.sh extract-files.sh
          ./setup-makefiles.sh
          ./extract-files.sh ~/holi
          cd ../..

      - name: Initialize and push to GitHub
        run: |
          cd vendor/oneplus/CPH2381
          git init
          git add .
          git commit -m "first commit"
          git branch -M main
          git remote add origin git@github.com:nobiraja/vendor_CPH2381.git
          git push -u origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
